title: Express TypeScript
description: ExpressTS (Express TypeScript) is decorator driven TypeScript framework on top of Express.js that allows you to use Express truly TypeScript way.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
